version: '3.8'
services:
  postgres:
    container_name: 'postgres'
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: concurrency
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
  redis:
    container_name: 'redis'
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
     - ./db-data/redis:/data
  mailhog:
    container_name: 'mailhog'
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
